INSERT OR IGNORE INTO users 
(telegram_id, name, gender, location_city, preference, bio, photo_url, is_onboarding_complete) 
VALUES
(221, 'Alya', 'FEMALE', 'Jakarta', 'EVERYONE', 'Book lover dan suka hujan malam.', 'https://i.pravatar.cc/400?img=1', 1),
(222, 'Bagas', 'MALE', 'Bandung', 'EVERYONE', 'Coffee addict dan suka roadtrip dadakan.', 'https://i.pravatar.cc/400?img=2', 1),
(223, 'Cindy', 'FEMALE', 'Surabaya', 'EVERYONE', 'Pecinta konser dan lagu galau.', 'https://i.pravatar.cc/400?img=3', 1),
(224, 'Dion', 'MALE', 'Bali', 'EVERYONE', 'Freelancer yang kerja sambil cari sunset.', 'https://i.pravatar.cc/400?img=4', 1),
(225, 'Elsa', 'FEMALE', 'Yogyakarta', 'EVERYONE', 'Suka museum, kopi, dan random talks.', 'https://i.pravatar.cc/400?img=5', 1),
(226, 'Farhan', 'MALE', 'Medan', 'EVERYONE', 'Ngoding sambil dengerin jazz.', 'https://i.pravatar.cc/400?img=6', 1),
(227, 'Gita', 'FEMALE', 'Bogor', 'EVERYONE', 'Dog person dan suka hiking.', 'https://i.pravatar.cc/400?img=7', 1),
(228, 'Hendra', 'MALE', 'Semarang', 'EVERYONE', 'Kuliner hunter sejati.', 'https://i.pravatar.cc/400?img=9', 1),
(229, 'Indah', 'FEMALE', 'Malang', 'EVERYONE', 'Calm outside, chaos inside.', 'https://i.pravatar.cc/400?img=10', 1),
(230, 'Jordi', 'MALE', 'Jakarta', 'EVERYONE', 'Suka futsal dan nongkrong sampai pagi.', 'https://i.pravatar.cc/400?img=12', 1),

(231, 'Kezia', 'FEMALE', 'Bandung', 'EVERYONE', 'Aesthetic cafe enthusiast.', 'https://i.pravatar.cc/400?img=13', 1),
(232, 'Lutfi', 'MALE', 'Bali', 'EVERYONE', 'Photographer yang suka candid moment.', 'https://i.pravatar.cc/400?img=14', 1),
(233, 'Mira', 'FEMALE', 'Surabaya', 'EVERYONE', 'Tukang ketawa walau receh.', 'https://i.pravatar.cc/400?img=17', 1),
(234, 'Niko', 'MALE', 'Bogor', 'EVERYONE', 'Motoran malam adalah terapi.', 'https://i.pravatar.cc/400?img=18', 1),
(235, 'Ocha', 'FEMALE', 'Jakarta', 'EVERYONE', 'Suka skincare dan tidur siang.', 'https://i.pravatar.cc/400?img=21', 1),
(236, 'Pras', 'MALE', 'Bandung', 'EVERYONE', 'Basket, kopi, repeat.', 'https://i.pravatar.cc/400?img=22', 1),
(237, 'Qory', 'FEMALE', 'Yogyakarta', 'EVERYONE', 'Suka nulis puisi random jam 2 pagi.', 'https://i.pravatar.cc/400?img=23', 1),
(238, 'Rendi', 'MALE', 'Semarang', 'EVERYONE', 'Anak rumahan tapi suka diajak jalan.', 'https://i.pravatar.cc/400?img=25', 1),
(239, 'Salsa', 'FEMALE', 'Bali', 'EVERYONE', 'Yoga, smoothie bowl, dan healing.', 'https://i.pravatar.cc/400?img=26', 1),
(240, 'Teguh', 'MALE', 'Jakarta', 'EVERYONE', 'Marketing by day, overthinker by night.', 'https://i.pravatar.cc/400?img=27', 1),

(241, 'Uli', 'FEMALE', 'Bandung', 'EVERYONE', 'Suka hujan dan lagu-lagu indie.', 'https://i.pravatar.cc/400?img=28', 1),
(242, 'Vino', 'MALE', 'Surabaya', 'EVERYONE', 'Gym tipis-tipis biar sehat.', 'https://i.pravatar.cc/400?img=29', 1),
(243, 'Wina', 'FEMALE', 'Bogor', 'EVERYONE', 'Bisa diem lama kalau udah nyaman.', 'https://i.pravatar.cc/400?img=30', 1),
(244, 'Yoga', 'MALE', 'Malang', 'EVERYONE', 'Suka camping dan kopi hitam.', 'https://i.pravatar.cc/400?img=31', 1),
(245, 'Zahra', 'FEMALE', 'Jakarta', 'EVERYONE', 'Obsessed with sunsets and playlists.', 'https://i.pravatar.cc/400?img=32', 1),
(246, 'Abel', 'MALE', 'Bali', 'EVERYONE', 'Designer yang hidupnya penuh revisi.', 'https://i.pravatar.cc/400?img=34', 1),
(247, 'Bianca', 'FEMALE', 'Semarang', 'EVERYONE', 'Kucingku prioritas utama.', 'https://i.pravatar.cc/400?img=35', 1),
(248, 'Chandra', 'MALE', 'Yogyakarta', 'EVERYONE', 'Film horror? Gas terus.', 'https://i.pravatar.cc/400?img=36', 1),
(249, 'Dara', 'FEMALE', 'Bandung', 'EVERYONE', 'Sarkas dikit tapi baik kok.', 'https://i.pravatar.cc/400?img=37', 1),
(250, 'Erik', 'MALE', 'Jakarta', 'EVERYONE', 'Sibuk kerja tapi selalu balas chat.', 'https://i.pravatar.cc/400?img=39', 1),

(251, 'Fina', 'FEMALE', 'Bali', 'EVERYONE', 'Beach girl with chaotic energy.', 'https://i.pravatar.cc/400?img=40', 1),
(252, 'Galih', 'MALE', 'Bogor', 'EVERYONE', 'Suka masak walau kadang gagal.', 'https://i.pravatar.cc/400?img=41', 1),
(253, 'Hani', 'FEMALE', 'Jakarta', 'EVERYONE', 'Matcha over coffee every day.', 'https://i.pravatar.cc/400?img=43', 1),
(254, 'Iqbal', 'MALE', 'Surabaya', 'EVERYONE', 'Pengabdi deadline.', 'https://i.pravatar.cc/400?img=46', 1),
(255, 'Jessie', 'FEMALE', 'Bandung', 'EVERYONE', 'Suka thrift shopping dan foto analog.', 'https://i.pravatar.cc/400?img=48', 1),
(256, 'Kris', 'MALE', 'Bali', 'EVERYONE', 'Traveling buat cari cerita baru.', 'https://i.pravatar.cc/400?img=50', 1),
(257, 'Lina', 'FEMALE', 'Yogyakarta', 'EVERYONE', 'Quiet girl with loud thoughts.', 'https://i.pravatar.cc/400?img=52', 1),
(258, 'Miko', 'MALE', 'Jakarta', 'EVERYONE', 'Ngopi sambil bahas teori konspirasi.', 'https://i.pravatar.cc/400?img=54', 1),
(259, 'Nisa', 'FEMALE', 'Semarang', 'EVERYONE', 'Suka spontaneous trip.', 'https://i.pravatar.cc/400?img=55', 1),
(260, 'Ojan', 'MALE', 'Bandung', 'EVERYONE', 'Kadang lucu, kadang ngilang.', 'https://i.pravatar.cc/400?img=56', 1),

(261, 'Pia', 'FEMALE', 'Jakarta', 'EVERYONE', 'Suka baking dan binge watching.', 'https://i.pravatar.cc/400?img=57', 1),
(262, 'Rifky', 'MALE', 'Bogor', 'EVERYONE', 'Cowok santai anti drama.', 'https://i.pravatar.cc/400?img=58', 1),
(263, 'Siska', 'FEMALE', 'Bali', 'EVERYONE', 'Healing terus sampai lupa pulang.', 'https://i.pravatar.cc/400?img=62', 1),
(264, 'Tomi', 'MALE', 'Medan', 'EVERYONE', 'Suka stand-up comedy dan kopi susu.', 'https://i.pravatar.cc/400?img=63', 1),
(265, 'Ucha', 'FEMALE', 'Surabaya', 'EVERYONE', 'Bisa jadi clingy kalau nyaman.', 'https://i.pravatar.cc/400?img=64', 1),
(266, 'Vicky', 'MALE', 'Jakarta', 'EVERYONE', 'Main game buat lari dari realita.', 'https://i.pravatar.cc/400?img=65', 1),
(267, 'Wulan', 'FEMALE', 'Bandung', 'EVERYONE', 'Pecinta langit sore.', 'https://i.pravatar.cc/400?img=66', 1),
(268, 'Yusuf', 'MALE', 'Yogyakarta', 'EVERYONE', 'Suka ngobrol random sampai pagi.', 'https://i.pravatar.cc/400?img=67', 1),
(269, 'Zeline', 'FEMALE', 'Jakarta', 'EVERYONE', 'Cafe hopping is my cardio.', 'https://i.pravatar.cc/400?img=69', 1),
(270, 'Andre', 'MALE', 'Bali', 'EVERYONE', 'Mencari teman sunset dan seafood.', 'https://i.pravatar.cc/400?img=70', 1);